### PR TITLE
wrap parsing in try-catch, to prevent it blowing up

### PR DESCRIPTION
**Pull request by cgrayson**
What do you think, @alexkwolfe?

### CODE REVIEW

**Comment by alexkwolfe** [comment]
Seems OK. I'd like to try to figure out what's wrong with the handler that it's not able to recover from an error in an integration though. Otherwise, we're relying on integrations to never throw an error.

**Comment by cgrayson** [comment]
Totally agree. But his will hopefully get a quick fix to Paul today.

**Comment by alexkwolfe** [comment]
I guess in order to reproduce it after this PR is merged, we'll have to just use an older version of the integration.

**Comment by cgrayson** [comment]
Yeah yeah. [Looking](https://github.com/activeprospect/leadconduit-handler/issues/90).

**Comment by cgrayson** [comment]
Travis errors due to some dependencies being newer than what I had locally. Maybe related to the "Invalid" in production. Still looking.

**Pull request merged**
